# Generated by Django 5.2.7 on 2025-11-05 14:26

import django.db.models.deletion
import lecture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lecture_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="강의 이름"
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        upload_to=lecture.models.audio_upload_path,
                        verbose_name="음성 파일",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to=lecture.models.pdf_upload_path,
                        verbose_name="PDF 파일",
                    ),
                ),
                (
                    "full_script",
                    models.TextField(
                        blank=True, null=True, verbose_name="전체 스크립트"
                    ),
                ),
                (
                    "summary_json",
                    models.JSONField(blank=True, null=True, verbose_name="요약 JSON"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "처리 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_topic", models.CharField(max_length=500)),
                ("mapped_pdf_page", models.IntegerField()),
                ("mapped_pdf_content", models.TextField()),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="lecture.lecture",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PdfChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_num", models.IntegerField()),
                ("content", models.TextField()),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="lecture.lecture",
                    ),
                ),
            ],
        ),
    ]
