# Generated by Django 5.2.7 on 2025-11-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="current_step",
            field=models.IntegerField(default=0, verbose_name="현재 진행 단계"),
        ),
    ]
