# Generated by Django 5.2.7 on 2025-11-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_stt_avg_sec_per_min",
                    models.FloatField(
                        default=10.0, verbose_name="오디오 STT 평균(초/분)"
                    ),
                ),
                (
                    "pdf_processing_avg_sec_per_page",
                    models.FloatField(
                        default=2.0, verbose_name="PDF 처리 평균(초/페이지)"
                    ),
                ),
                (
                    "summary_avg_sec",
                    models.FloatField(default=30.0, verbose_name="요약 평균(초)"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="업데이트 일시"),
                ),
            ],
            options={
                "verbose_name": "처리 통계",
                "verbose_name_plural": "처리 통계",
            },
        ),
        migrations.AddField(
            model_name="lecture",
            name="estimated_time_sec",
            field=models.IntegerField(default=0, verbose_name="예상 소요 시간(초)"),
        ),
    ]
