# Generated by Django 5.2.7 on 2025-11-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0002_processingstats_lecture_estimated_time_sec"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="step_times",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="단계별 소요 시간"
            ),
        ),
    ]
