# Generated by Django 5.2.7 on 2025-11-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0003_lecture_step_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingstats",
            name="embedding_avg_sec_per_page",
            field=models.FloatField(default=0.8, verbose_name="임베딩 평균(초/페이지)"),
        ),
        migrations.AddField(
            model_name="processingstats",
            name="pdf_parsing_avg_sec_per_page",
            field=models.FloatField(
                default=0.8, verbose_name="PDF 파싱 평균(초/페이지)"
            ),
        ),
    ]
