# Generated by Django 5.2.7 on 2025-11-12 12:59

import lecture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0004_processingstats_embedding_avg_sec_per_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="youtube_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="YouTube URL"
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=lecture.models.audio_upload_path,
                verbose_name="음성 파일",
            ),
        ),
    ]
