# Generated by Django 5.2.7 on 2025-11-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0005_lecture_youtube_url_alter_lecture_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="youtube_download_eta_sec",
            field=models.IntegerField(
                default=0, verbose_name="YouTube 다운로드 ETA(초)"
            ),
        ),
    ]
