# Generated by Django 5.2.7 on 2025-11-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0006_lecture_youtube_download_eta_sec"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="관리자 페이지 접근 권한을 가진 사용자인지 여부",
                verbose_name="관리자 여부",
            ),
        ),
    ]
