# Generated by Django 5.2.7 on 2025-11-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0007_customuser_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_admin",
        ),
    ]
