# Generated by Django 5.2.7 on 2025-11-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0008_remove_customuser_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processingstats",
            name="pdf_processing_avg_sec_per_page",
        ),
    ]
