# Generated by Django 5.2.7 on 2025-11-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0009_remove_processingstats_pdf_processing_avg_sec_per_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processingstats",
            name="summary_avg_sec",
        ),
        migrations.AddField(
            model_name="processingstats",
            name="summary_avg_sec_per_min",
            field=models.FloatField(default=1.0, verbose_name="요약 평균(초/분)"),
        ),
        migrations.AlterField(
            model_name="processingstats",
            name="audio_stt_avg_sec_per_min",
            field=models.FloatField(default=2.0, verbose_name="오디오 STT 평균(초/분)"),
        ),
        migrations.AlterField(
            model_name="processingstats",
            name="embedding_avg_sec_per_page",
            field=models.FloatField(
                default=0.07, verbose_name="임베딩 평균(초/페이지)"
            ),
        ),
        migrations.AlterField(
            model_name="processingstats",
            name="pdf_parsing_avg_sec_per_page",
            field=models.FloatField(
                default=1.6, verbose_name="PDF 파싱 평균(초/페이지)"
            ),
        ),
    ]
