"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent
# 2. django-environ 초기 설정 (파일 상단에 추가)
env = environ.Env(
    # (선택사항) 기본값 설정
    DEBUG=(bool, False)
)

# 3. .env 파일 읽어오기 (BASE_DIR에 있는 .env 파일을 읽음)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# CSRF 설정
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']
CSRF_COOKIE_SECURE = False  # 개발 환경에서는 False
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = False  # 개발 환경에서는 False


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "lecture",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 2. Gemini API 키 (Streamlit secrets 대신 환경 변수나 .env 사용)
GEMINI_API_KEY = env('GEMINI_API_KEY')
# (기존 secrets.toml의 키를 .env 파일 등으로 옮겨야 함)

# 3. 모델 이름 (Streamlit의 config.py에서 가져옴)
MODEL_FLASH = 'gemini-2.5-flash'
MODEL_EMBEDDING = 'models/text-embedding-004'

# 4. 파일 업로드 경로 (Streamlit의 config.py 대체)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_uploads') # ./media_uploads 폴더

# 5. ChromaDB 경로
CHROMA_PATH = os.path.join(BASE_DIR, 'chroma_db')

# 6. Celery 설정 (비동기 작업용)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Celery 작업 안정성 설정
# task_acks_late=True: 작업이 완료된 후에만 메시지를 확인 처리 (작업 손실 방지)
# task_reject_on_worker_lost=True: 워커가 중단되면 작업을 다시 큐에 반환
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# 7. 인증 설정
AUTH_USER_MODEL = 'lecture.CustomUser'  # 커스텀 User 모델 사용
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# 8. Ollama 설정
OLLAMA_BASE_URL = env('OLLAMA_BASE_URL', default='http://localhost:11434')
OLLAMA_MODEL = env('OLLAMA_MODEL', default='bakllava')  # bakllava 또는 llava
OLLAMA_BATCH_SIZE = int(env('OLLAMA_BATCH_SIZE', default='4'))  # 배치 크기 (병렬 처리)
OLLAMA_TIMEOUT = int(env('OLLAMA_TIMEOUT', default='30'))  # Ollama 요청 타임아웃 (초)
OLLAMA_MAX_RETRIES = int(env('OLLAMA_MAX_RETRIES', default='2'))  # 최대 재시도 횟수